const theme = {
    light: {
        theme: 'light',
        bg: '#FFFFFF',
        bg2:'#FFFFFF',
        bg3:'#F8F8F8',
        txt: '#013220',//figma color
        txt2: '#424242',
        txt3: '#616161',
        disable: '#9E9E9E',
        border: '#EEEEEE',
        input: '#FAFAFA',
        skip: '#E9F8F5',
        chat:'#F5F5F5',
        indi: '#E0E0E0',
        skip1:'#E6F8EF',
        btn: '#E8F8EF',
        btntxt: '#01B763',

        c1: require('../../assets/image/c1.png'),
        s10: require('../../assets/image/s10.png'),
        fruits_bgr: require('../../assets/image/fruits_bgr.png'),
        a: require('../../assets/image/a.png'),
        a1: require('../../assets/image/a1.png'),
        apple: require('../../assets/image/Appled.png'),
        a2: require('../../assets/image/a2.png'),
        a3: require('../../assets/image/a3.png'),
        a7: require('../../assets/image/a7.png'),
        a9: require('../../assets/image/a9.png'),
        a12: require('../../assets/image/a12.png'),
        demoUser: require('../../assets/image/demoUser.png'),
        basket: require('../../assets/image/basket.png'),
    },
    dark: {
        theme: 'dark',
        bg: '#181A20',
        bg2:'#1F222A',
        bg3:'#35383F',
        txt: '#FFFFFF',
        txt2: '#E0E0E0',
        txt3: '#E0E0E0',
        disable: '#FFFFFF',
        border: '#35383F',
        input: '#1F222A',
        skip: '#E6F8EF',
        chat:'#35383F',
        indi: '#35383F',
        skip1:'#35383F',
        btn: '#35383F',
        btntxt: '#FFFFFF',

        c1: require('../../assets/image/c1d.png'),
        s10: require('../../assets/image/s10d.png'),

        a: require('../../assets/image/ad.png'),
        a1: require('../../assets/image/a1d.png'),
        apple: require('../../assets/image/Apple.png'),
        a2: require('../../assets/image/a2d.png'),
        a3: require('../../assets/image/a3d.png'),
        a7: require('../../assets/image/a7d.png'),
        a9: require('../../assets/image/a9d.png'),
        a12: require('../../assets/image/a12d.png'),
        demoUser: require('../../assets/image/demoUser.png'),
        basket: require('../../assets/image/basket.png'),
    },

};

export default theme;